// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeVariables(theme string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if theme == "nord" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Nord */\n\t\t\t\t--bg-primary: #2E3440;\n\t\t\t\t--bg-secondary: #3B4252;\n\t\t\t\t--text-primary: #ECEFF4;\n\t\t\t\t--text-secondary: #D8DEE9;\n\t\t\t\t--accent-primary: #88C0D0;\n\t\t\t\t--accent-danger: #BF616A;\n\t\t\t\t--border-color: #4C566A;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if theme == "gruvbox" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Gruvbox */\n\t\t\t\t--bg-primary: #282828;\n\t\t\t\t--bg-secondary: #3c3836;\n\t\t\t\t--text-primary: #ebdbb2;\n\t\t\t\t--text-secondary: #d5c4a1;\n\t\t\t\t--accent-primary: #fabd2f;\n\t\t\t\t--accent-danger: #fb4934;\n\t\t\t\t--border-color: #504945;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<style>\n\t\t\t:root {\n\t\t\t\t/* Palette - Rosé Pine Moon (Default) */\n\t\t\t\t--bg-primary: #232136;\n\t\t\t\t--bg-secondary: #2a273f;\n\t\t\t\t--text-primary: #e0def4;\n\t\t\t\t--text-secondary: #908caa;\n\t\t\t\t--accent-primary: #c4a7e7;\n\t\t\t\t--accent-danger: #ea9a97;\n\t\t\t\t--border-color: #393552;\n\t\t\t}\n\t\t</style>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
